version: 1

formatters:
  simple:
    format: "%(levelname)-8s - %(funcName)-20s - %(message)s"
  verbose:
    format: "%(asctime)s - %(levelname)-8s - %(funcName)-26s - %(message)s"
    datefmt: '%Y-%M-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: verbose
    filename: logs/app-run.log

loggers:
  "__main__":
    level: DEBUG
    handlers: [console,file]
    propagate: no
